services:
  caddy:
    image: caddy:2-alpine
    container_name: go-app-caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - caddy_data:/data
      - caddy_config:/config

    command:
      - caddy
      - reverse-proxy
      - --from
      - www.chat-app.website
      - --to
      - go-app-frontend:80

    networks:
      - go-app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  go-app-network:
    external: true
    name: go-app-network