services:
  frontend:
    image: ghcr.io/harrydo29/go-app-ui:latest
    container_name: go-app-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    networks:
      - go-app-network

networks:
  go-app-network:
    external: true
    name: go-app-network